version: "3.8"
services:
  frontend:
    build:
      context: ./hotelmanager_frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./hotelmanager_frontend/dist:/app
    networks:
      - spring-angular-network
    depends_on:
      - springboot-be

  springboot-be:
    image: hotelmanager
    build:
      context: ./hotelmanager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-angular-network
    environment:
      SPRING_PROFILES_ACTIVE: 'test-profile'
      # DEBUG: 'true'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hotelmanager_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=testuser'
    ports:
      - '5432:5432'
    networks:
      - spring-angular-network
  adminer:
      image: adminer
      ports:
        - "8081:8080"
      networks:
        - spring-angular-network
      depends_on:
        - postgres

networks:
  spring-angular-network:
    driver: bridge